version: "3"
services:
  mongo:
    image: mongo:4.0
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
    expose:
      - 27017
      - 27018
      - 27019
    networks:
      - webnet
    restart: always
networks:
  webnet:
volumes:
  data:
  